"""Shared thresholds and defaults used by the MVP backend."""

DEMOGRAPHIC_PARITY_THRESHOLD = 0.10
EQUAL_OPPORTUNITY_THRESHOLD = 0.10
DISPARATE_IMPACT_THRESHOLD = 0.80
PREDICTIVE_PARITY_THRESHOLD = 0.10
ACCURACY_EQUITY_THRESHOLD = 0.05
FNR_DISPARITY_THRESHOLD = 0.10

PROXY_CORRELATION_THRESHOLD = 0.30

MIN_GROUP_SIZE = 30
MIN_TOTAL_ROWS = 50
MAX_INTERSECTIONAL_GROUPS = 20

DEFAULT_AGE_BINS = [0, 18, 25, 35, 50, 65, 100]
DEFAULT_AGE_LABELS = ["<18", "18-25", "26-35", "36-50", "51-65", "65+"]

SEVERITY_CRITICAL = "critical"
SEVERITY_WARNING = "warning"
SEVERITY_INFO = "info"

SUPPORTED_UPLOAD_SUFFIXES = {".csv", ".xlsx", ".xls"}
